version: '3.8'
services:
  lavadero-api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=lavadero
    depends_on:
      - redis
      - database
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    logging:
      driver: 'json-file'

  database:
    image: postgres:14
    container_name: lavadero-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: lavadero
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: 'json-file'

volumes:
  db-data:
