version: '3.8'
services:
  lavadero-api:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
    depends_on:
      - redis
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  redis:
    image: redis:6-alpine
    ports:
      - '6379:6379'
    logging:
      driver: 'json-file'
