version: '3.8'
services:
  lavadero-api:
    build: .
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - redis
      - database
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

  redis:
    image: redis:6-alpine
    ports:
      - '${REDIS_PORT}:${REDIS_PORT}'
    env_file:
      - .env
    logging:
      driver: 'json-file'

  database:
    image: postgres:14
    container_name: lavadero-db
    env_file:
      - .env
    ports:
      - '${DB_PORT}:${DB_PORT}'
    volumes:
      - db-data:/var/lib/postgresql/data
    logging:
      driver: 'json-file'

volumes:
  db-data:
